services:
  idle-steam:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: idle-steam
    restart: unless-stopped
    user: "${PUID:-1000}:${PGID:-1000}"
    env_file: .env
    environment:
      NODE_OPTIONS: --disable-warning=ExperimentalWarning
    networks:
      - main-network
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

networks:
  main-network:
    external: true
    name: main-gateway
